// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 12.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace CodedUIMultiTabBrowser
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.HtmlControls;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "12.0.30501.0")]
    public partial class UIMap
    {
        
        /// <summary>
        /// RecordedMethod1
        /// </summary>
        public void RecordedMethod1()
        {
            #region Variable Declarations
            HtmlHyperlink uICreatenewTABHyperlink = this.UIHomePageMyASPNETApplWindow.UIHomePageMyASPNETApplDocument.UICreatenewTABHyperlink;
            WinTabPage uIHomePageMyASPNETApplTabPage = this.UIHomePageMyASPNETApplWindow.UITabRowTabList.UIHomePageMyASPNETApplTabPage;
            WinTabPage uINewTabTabGroup2TabPage = this.UIHomePageMyASPNETApplWindow.UITabRowTabList.UINewTabTabGroup2TabPage;
            #endregion

            // Click 'Create new TAB' link
            Mouse.Click(uICreatenewTABHyperlink, new Point(116, 28));

            // Click 'Home Page - My ASP.NET Application Tab Group 2' tab
            Mouse.Click(uIHomePageMyASPNETApplTabPage, new Point(39, 13));

            // Click 'Create new TAB' link
            Mouse.Click(uICreatenewTABHyperlink, new Point(80, 25));

            // Click 'Home Page - My ASP.NET Application Tab Group 2' tab
            Mouse.Click(uIHomePageMyASPNETApplTabPage, new Point(110, 10));

            // Click 'Create new TAB' link
            Mouse.Click(uICreatenewTABHyperlink, new Point(54, 24));

            // Click 'New Tab Tab Group 2' tab
            Mouse.Click(uINewTabTabGroup2TabPage, new Point(90, 22));
        }
        
        #region Properties
        public UIHomePageMyASPNETApplWindow UIHomePageMyASPNETApplWindow
        {
            get
            {
                if ((this.mUIHomePageMyASPNETApplWindow == null))
                {
                    this.mUIHomePageMyASPNETApplWindow = new UIHomePageMyASPNETApplWindow();
                }
                return this.mUIHomePageMyASPNETApplWindow;
            }
        }
        
        public UIBingInternetExplorerWindow UIBingInternetExplorerWindow
        {
            get
            {
                if ((this.mUIBingInternetExplorerWindow == null))
                {
                    this.mUIBingInternetExplorerWindow = new UIBingInternetExplorerWindow();
                }
                return this.mUIBingInternetExplorerWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIHomePageMyASPNETApplWindow mUIHomePageMyASPNETApplWindow;
        
        private UIBingInternetExplorerWindow mUIBingInternetExplorerWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.30501.0")]
    public class UIHomePageMyASPNETApplWindow : BrowserWindow
    {
        
        public UIHomePageMyASPNETApplWindow()
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.Name] = "Home Page - My ASP.NET Application";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("Home Page - My ASP.NET Application");
            this.WindowTitles.Add("New Tab");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public UIHomePageMyASPNETApplDocument UIHomePageMyASPNETApplDocument
        {
            get
            {
                if ((this.mUIHomePageMyASPNETApplDocument == null))
                {
                    this.mUIHomePageMyASPNETApplDocument = new UIHomePageMyASPNETApplDocument(this);
                }
                return this.mUIHomePageMyASPNETApplDocument;
            }
        }
        
        public UITabRowTabList UITabRowTabList
        {
            get
            {
                if ((this.mUITabRowTabList == null))
                {
                    this.mUITabRowTabList = new UITabRowTabList(this);
                }
                return this.mUITabRowTabList;
            }
        }
        
        public UINewTabDocument UINewTabDocument
        {
            get
            {
                if ((this.mUINewTabDocument == null))
                {
                    this.mUINewTabDocument = new UINewTabDocument(this);
                }
                return this.mUINewTabDocument;
            }
        }
        
        public UINewTabTabGroup1TabPage UINewTabTabGroup1TabPage
        {
            get
            {
                if ((this.mUINewTabTabGroup1TabPage == null))
                {
                    this.mUINewTabTabGroup1TabPage = new UINewTabTabGroup1TabPage(this);
                }
                return this.mUINewTabTabGroup1TabPage;
            }
        }
        #endregion
        
        #region Fields
        private UIHomePageMyASPNETApplDocument mUIHomePageMyASPNETApplDocument;
        
        private UITabRowTabList mUITabRowTabList;
        
        private UINewTabDocument mUINewTabDocument;
        
        private UINewTabTabGroup1TabPage mUINewTabTabGroup1TabPage;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.30501.0")]
    public class UIHomePageMyASPNETApplDocument : HtmlDocument
    {
        
        public UIHomePageMyASPNETApplDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Home Page - My ASP.NET Application";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://localhost:7032/";
            this.WindowTitles.Add("Home Page - My ASP.NET Application");
            #endregion
        }
        
        #region Properties
        public HtmlHyperlink UICreatenewTABHyperlink
        {
            get
            {
                if ((this.mUICreatenewTABHyperlink == null))
                {
                    this.mUICreatenewTABHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUICreatenewTABHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = "newTabHyperlink";
                    this.mUICreatenewTABHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUICreatenewTABHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = "_blank";
                    this.mUICreatenewTABHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "Create new TAB";
                    this.mUICreatenewTABHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/Home/NewTab";
                    this.mUICreatenewTABHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUICreatenewTABHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "http://localhost:7032/Home/NewTab";
                    this.mUICreatenewTABHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = "btn btn-primary btn-lg";
                    this.mUICreatenewTABHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "class=\"btn btn-primary btn-lg\" id=\"newTa";
                    this.mUICreatenewTABHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "7";
                    this.mUICreatenewTABHyperlink.WindowTitles.Add("Home Page - My ASP.NET Application");
                    #endregion
                }
                return this.mUICreatenewTABHyperlink;
            }
        }
        #endregion
        
        #region Fields
        private HtmlHyperlink mUICreatenewTABHyperlink;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.30501.0")]
    public class UITabRowTabList : WinTabList
    {
        
        public UITabRowTabList(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinTabList.PropertyNames.Name] = "Tab Row";
            this.WindowTitles.Add("New Tab");
            #endregion
        }
        
        #region Properties
        public WinTabPage UIHomePageMyASPNETApplTabPage
        {
            get
            {
                if ((this.mUIHomePageMyASPNETApplTabPage == null))
                {
                    this.mUIHomePageMyASPNETApplTabPage = new WinTabPage(this);
                    #region Search Criteria
                    this.mUIHomePageMyASPNETApplTabPage.SearchProperties[WinTabPage.PropertyNames.Name] = "Home Page - My ASP.NET Application Tab Group 2";
                    this.mUIHomePageMyASPNETApplTabPage.WindowTitles.Add("New Tab");
                    #endregion
                }
                return this.mUIHomePageMyASPNETApplTabPage;
            }
        }
        
        public WinTabPage UINewTabTabGroup2TabPage
        {
            get
            {
                if ((this.mUINewTabTabGroup2TabPage == null))
                {
                    this.mUINewTabTabGroup2TabPage = new WinTabPage(this);
                    #region Search Criteria
                    this.mUINewTabTabGroup2TabPage.SearchProperties[WinTabPage.PropertyNames.Name] = "New Tab Tab Group 2";
                    this.mUINewTabTabGroup2TabPage.WindowTitles.Add("New Tab");
                    #endregion
                }
                return this.mUINewTabTabGroup2TabPage;
            }
        }
        
        public WinTabPage UINewTabTabGroup1TabPage
        {
            get
            {
                if ((this.mUINewTabTabGroup1TabPage == null))
                {
                    this.mUINewTabTabGroup1TabPage = new WinTabPage(this);
                    #region Search Criteria
                    this.mUINewTabTabGroup1TabPage.SearchProperties[WinTabPage.PropertyNames.Name] = "New Tab Tab Group 1";
                    this.mUINewTabTabGroup1TabPage.SearchProperties[WinTabPage.PropertyNames.Instance] = "2";
                    this.mUINewTabTabGroup1TabPage.WindowTitles.Add("New Tab");
                    #endregion
                }
                return this.mUINewTabTabGroup1TabPage;
            }
        }
        #endregion
        
        #region Fields
        private WinTabPage mUIHomePageMyASPNETApplTabPage;
        
        private WinTabPage mUINewTabTabGroup2TabPage;
        
        private WinTabPage mUINewTabTabGroup1TabPage;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.30501.0")]
    public class UINewTabDocument : HtmlDocument
    {
        
        public UINewTabDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "New Tab";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/Home/NewTab";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://localhost:7032/Home/NewTab";
            this.WindowTitles.Add("New Tab");
            #endregion
        }
        
        #region Properties
        public HtmlDiv UIThisistheinnertext29Pane
        {
            get
            {
                if ((this.mUIThisistheinnertext29Pane == null))
                {
                    this.mUIThisistheinnertext29Pane = new HtmlDiv(this);
                    #region Search Criteria
                    this.mUIThisistheinnertext29Pane.SearchProperties[HtmlDiv.PropertyNames.Id] = "itemToFind";
                    this.mUIThisistheinnertext29Pane.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
                    this.mUIThisistheinnertext29Pane.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "This is the inner text 29 ";
                    this.mUIThisistheinnertext29Pane.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
                    this.mUIThisistheinnertext29Pane.FilterProperties[HtmlDiv.PropertyNames.Class] = null;
                    this.mUIThisistheinnertext29Pane.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "id=\"itemToFind\"";
                    this.mUIThisistheinnertext29Pane.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "1";
                    this.mUIThisistheinnertext29Pane.WindowTitles.Add("New Tab");
                    #endregion
                }
                return this.mUIThisistheinnertext29Pane;
            }
        }
        #endregion
        
        #region Fields
        private HtmlDiv mUIThisistheinnertext29Pane;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.30501.0")]
    public class UINewTabTabGroup1TabPage : WinTabPage
    {
        
        public UINewTabTabGroup1TabPage(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinTabPage.PropertyNames.Name] = "New Tab Tab Group 1";
            this.WindowTitles.Add("New Tab");
            #endregion
        }
        
        #region Properties
        public WinButton UICloseTabCtrlWButton
        {
            get
            {
                if ((this.mUICloseTabCtrlWButton == null))
                {
                    this.mUICloseTabCtrlWButton = new WinButton(this);
                    #region Search Criteria
                    this.mUICloseTabCtrlWButton.SearchProperties[WinButton.PropertyNames.Name] = "Close Tab (Ctrl+W)";
                    this.mUICloseTabCtrlWButton.WindowTitles.Add("New Tab");
                    #endregion
                }
                return this.mUICloseTabCtrlWButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUICloseTabCtrlWButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.30501.0")]
    public class UIBingInternetExplorerWindow : BrowserWindow
    {
        
        public UIBingInternetExplorerWindow()
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.Name] = "Bing";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("Bing");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public UIBingTabPage UIBingTabPage
        {
            get
            {
                if ((this.mUIBingTabPage == null))
                {
                    this.mUIBingTabPage = new UIBingTabPage(this);
                }
                return this.mUIBingTabPage;
            }
        }
        #endregion
        
        #region Fields
        private UIBingTabPage mUIBingTabPage;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.30501.0")]
    public class UIBingTabPage : WinTabPage
    {
        
        public UIBingTabPage(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinTabPage.PropertyNames.Name] = "Bing";
            this.WindowTitles.Add("Bing");
            #endregion
        }
        
        #region Properties
        public WinButton UICloseTabCtrlWButton
        {
            get
            {
                if ((this.mUICloseTabCtrlWButton == null))
                {
                    this.mUICloseTabCtrlWButton = new WinButton(this);
                    #region Search Criteria
                    this.mUICloseTabCtrlWButton.SearchProperties[WinButton.PropertyNames.Name] = "Close Tab (Ctrl+W)";
                    this.mUICloseTabCtrlWButton.WindowTitles.Add("Bing");
                    #endregion
                }
                return this.mUICloseTabCtrlWButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUICloseTabCtrlWButton;
        #endregion
    }
}
