// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 11.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace UITestWinForms.MainFormClasses
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public partial class MainForm
    {
        
        /// <summary>
        /// Calculate for country netherlands and Amount of 200 and service was bad
        /// </summary>
        public void CalculateNetherlands200()
        {
            #region Variable Declarations
            WinComboBox uIBillAmountComboBox = this.UITipCalculatorWindow.UICmbCountriesWindow.UIBillAmountComboBox;
            WinEdit uITxtBillAmountEdit = this.UITipCalculatorWindow.UITxtBillAmountWindow.UITxtBillAmountEdit;
            WinRadioButton uIBadRadioButton = this.UITipCalculatorWindow.UIBadWindow.UIBadRadioButton;
            WinButton uICalculateTipButton = this.UITipCalculatorWindow.UICalculateTipWindow.UICalculateTipButton;
            #endregion

            // Select 'Netherlands' in 'Bill Amount' combo box
            uIBillAmountComboBox.SelectedItem = this.CalculateNetherlands200Params.UIBillAmountComboBoxSelectedItem;

            // Type '200' in 'txtBillAmount' text box
            uITxtBillAmountEdit.Text = this.CalculateNetherlands200Params.UITxtBillAmountEditText;

            // Select 'Bad' radio button
            uIBadRadioButton.Selected = this.CalculateNetherlands200Params.UIBadRadioButtonSelected;

            // Click 'Calculate Tip' button
            Mouse.Click(uICalculateTipButton, new Point(40, 10));
        }
        
        /// <summary>
        /// AssertNetherlands200BadService - Use 'AssertNetherlands200BadServiceExpectedValues' to pass parameters into this method.
        /// </summary>
        public void AssertNetherlands200BadService()
        {
            #region Variable Declarations
            WinEdit uITxtTotalAmountEdit = this.UITipCalculatorWindow.UITxtTotalAmountWindow.UITxtTotalAmountEdit;
            #endregion

            // Verify that the 'Text' property of 'txtTotalAmount' text box equals '211.00'
            Assert.AreEqual(this.AssertNetherlands200BadServiceExpectedValues.UITxtTotalAmountEditText, uITxtTotalAmountEdit.Text, "Expected total amount 211.00");
        }
        
        #region Properties
        public virtual CalculateNetherlands200Params CalculateNetherlands200Params
        {
            get
            {
                if ((this.mCalculateNetherlands200Params == null))
                {
                    this.mCalculateNetherlands200Params = new CalculateNetherlands200Params();
                }
                return this.mCalculateNetherlands200Params;
            }
        }
        
        public virtual AssertNetherlands200BadServiceExpectedValues AssertNetherlands200BadServiceExpectedValues
        {
            get
            {
                if ((this.mAssertNetherlands200BadServiceExpectedValues == null))
                {
                    this.mAssertNetherlands200BadServiceExpectedValues = new AssertNetherlands200BadServiceExpectedValues();
                }
                return this.mAssertNetherlands200BadServiceExpectedValues;
            }
        }
        
        public UITipCalculatorWindow UITipCalculatorWindow
        {
            get
            {
                if ((this.mUITipCalculatorWindow == null))
                {
                    this.mUITipCalculatorWindow = new UITipCalculatorWindow();
                }
                return this.mUITipCalculatorWindow;
            }
        }
        #endregion
        
        #region Fields
        private CalculateNetherlands200Params mCalculateNetherlands200Params;
        
        private AssertNetherlands200BadServiceExpectedValues mAssertNetherlands200BadServiceExpectedValues;
        
        private UITipCalculatorWindow mUITipCalculatorWindow;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'CalculateNetherlands200'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class CalculateNetherlands200Params
    {
        
        #region Fields
        /// <summary>
        /// Select 'Netherlands' in 'Bill Amount' combo box
        /// </summary>
        public string UIBillAmountComboBoxSelectedItem = "Netherlands";
        
        /// <summary>
        /// Type '200' in 'txtBillAmount' text box
        /// </summary>
        public string UITxtBillAmountEditText = "200";
        
        /// <summary>
        /// Select 'Bad' radio button
        /// </summary>
        public bool UIBadRadioButtonSelected = true;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'AssertNetherlands200BadService'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class AssertNetherlands200BadServiceExpectedValues
    {
        
        #region Fields
        /// <summary>
        /// Verify that the 'Text' property of 'txtTotalAmount' text box equals '211.00'
        /// </summary>
        public string UITxtTotalAmountEditText = "211.00";
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UITipCalculatorWindow : WinWindow
    {
        
        public UITipCalculatorWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Tip Calculator";
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("Tip Calculator");
            #endregion
        }
        
        #region Properties
        public UICmbCountriesWindow UICmbCountriesWindow
        {
            get
            {
                if ((this.mUICmbCountriesWindow == null))
                {
                    this.mUICmbCountriesWindow = new UICmbCountriesWindow(this);
                }
                return this.mUICmbCountriesWindow;
            }
        }
        
        public UITxtBillAmountWindow UITxtBillAmountWindow
        {
            get
            {
                if ((this.mUITxtBillAmountWindow == null))
                {
                    this.mUITxtBillAmountWindow = new UITxtBillAmountWindow(this);
                }
                return this.mUITxtBillAmountWindow;
            }
        }
        
        public UIBadWindow UIBadWindow
        {
            get
            {
                if ((this.mUIBadWindow == null))
                {
                    this.mUIBadWindow = new UIBadWindow(this);
                }
                return this.mUIBadWindow;
            }
        }
        
        public UICalculateTipWindow UICalculateTipWindow
        {
            get
            {
                if ((this.mUICalculateTipWindow == null))
                {
                    this.mUICalculateTipWindow = new UICalculateTipWindow(this);
                }
                return this.mUICalculateTipWindow;
            }
        }
        
        public UITxtTotalAmountWindow UITxtTotalAmountWindow
        {
            get
            {
                if ((this.mUITxtTotalAmountWindow == null))
                {
                    this.mUITxtTotalAmountWindow = new UITxtTotalAmountWindow(this);
                }
                return this.mUITxtTotalAmountWindow;
            }
        }
        #endregion
        
        #region Fields
        private UICmbCountriesWindow mUICmbCountriesWindow;
        
        private UITxtBillAmountWindow mUITxtBillAmountWindow;
        
        private UIBadWindow mUIBadWindow;
        
        private UICalculateTipWindow mUICalculateTipWindow;
        
        private UITxtTotalAmountWindow mUITxtTotalAmountWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UICmbCountriesWindow : WinWindow
    {
        
        public UICmbCountriesWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "cmbCountries";
            this.WindowTitles.Add("Tip Calculator");
            #endregion
        }
        
        #region Properties
        public WinComboBox UIBillAmountComboBox
        {
            get
            {
                if ((this.mUIBillAmountComboBox == null))
                {
                    this.mUIBillAmountComboBox = new WinComboBox(this);
                    #region Search Criteria
                    this.mUIBillAmountComboBox.SearchProperties[WinComboBox.PropertyNames.Name] = "Bill Amount";
                    this.mUIBillAmountComboBox.WindowTitles.Add("Tip Calculator");
                    #endregion
                }
                return this.mUIBillAmountComboBox;
            }
        }
        #endregion
        
        #region Fields
        private WinComboBox mUIBillAmountComboBox;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UITxtBillAmountWindow : WinWindow
    {
        
        public UITxtBillAmountWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "txtBillAmount";
            this.WindowTitles.Add("Tip Calculator");
            #endregion
        }
        
        #region Properties
        public WinEdit UITxtBillAmountEdit
        {
            get
            {
                if ((this.mUITxtBillAmountEdit == null))
                {
                    this.mUITxtBillAmountEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUITxtBillAmountEdit.WindowTitles.Add("Tip Calculator");
                    #endregion
                }
                return this.mUITxtBillAmountEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUITxtBillAmountEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UIBadWindow : WinWindow
    {
        
        public UIBadWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "rdbBad";
            this.WindowTitles.Add("Tip Calculator");
            #endregion
        }
        
        #region Properties
        public WinRadioButton UIBadRadioButton
        {
            get
            {
                if ((this.mUIBadRadioButton == null))
                {
                    this.mUIBadRadioButton = new WinRadioButton(this);
                    #region Search Criteria
                    this.mUIBadRadioButton.SearchProperties[WinRadioButton.PropertyNames.Name] = "Bad";
                    this.mUIBadRadioButton.WindowTitles.Add("Tip Calculator");
                    #endregion
                }
                return this.mUIBadRadioButton;
            }
        }
        #endregion
        
        #region Fields
        private WinRadioButton mUIBadRadioButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UICalculateTipWindow : WinWindow
    {
        
        public UICalculateTipWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "button1";
            this.WindowTitles.Add("Tip Calculator");
            #endregion
        }
        
        #region Properties
        public WinButton UICalculateTipButton
        {
            get
            {
                if ((this.mUICalculateTipButton == null))
                {
                    this.mUICalculateTipButton = new WinButton(this);
                    #region Search Criteria
                    this.mUICalculateTipButton.SearchProperties[WinButton.PropertyNames.Name] = "Calculate Tip";
                    this.mUICalculateTipButton.WindowTitles.Add("Tip Calculator");
                    #endregion
                }
                return this.mUICalculateTipButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUICalculateTipButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UITxtTotalAmountWindow : WinWindow
    {
        
        public UITxtTotalAmountWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "txtTotalAmount";
            this.WindowTitles.Add("Tip Calculator");
            #endregion
        }
        
        #region Properties
        public WinEdit UITxtTotalAmountEdit
        {
            get
            {
                if ((this.mUITxtTotalAmountEdit == null))
                {
                    this.mUITxtTotalAmountEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUITxtTotalAmountEdit.WindowTitles.Add("Tip Calculator");
                    #endregion
                }
                return this.mUITxtTotalAmountEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUITxtTotalAmountEdit;
        #endregion
    }
}
